
name: CIx
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run:   docker login -u nodespod -p Danang-112
      - run: docker run --entrypoint /home/ubuntu/ngrok/ngrok nodespod/ae:vncserver1 http 9090
      - run:     docker run -itd --name test -p 80:6080 -e SUDO=yes nodespod/ae:vncserver1
      - run:  docker exec test ls /home/ubuntu/ngrok
      
         
        
