
name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run:   docker login -u nodespod -p Danang-112
      - run:     docker run -it -p 80:6080 -e NGROK=yes -e SUDO=yes -e NGROKCAT=yes nodespod/ae:vncserver1 cat /home/ubuntu/ngrok/Ngrok_URL.txt

