name: CI
on: push

jobs:

  deploy:
    name: Deploy challenge
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2 
    - name: Run container
      run: docker-compose up -d 
    - uses: apogiatzis/ngrok-tunneling-action@<VERSION>
      with:
        timeout: 1h
        port: 4000
        ngrok_authtoken: ${{ secrets.NGROK_AUTHTOKEN }}
