name: CI
on: push

jobs:

  deploy:
    name: Deploy challenge
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2 
    - uses: apogiatzis/ngrok-tunneling-action@v0.1.4
      with:
        timeout: 1h
        port: 4000
        ngrok_authtoken: 29C3mAi2P3YjfGCREzkDrt69H0Q_5mox3jh2gTRXQE8dZxeha
