name: Test

on: [push]

jobs:
  testsolaris:
    runs-on: macos-latest
    name: Test a ngrok tunnel
    env:
      NGROK_TOKEN : 29C3mAi2P3YjfGCREzkDrt69H0Q_5mox3jh2gTRXQE8dZxeha
    steps:
    - uses: actions/checkout@v2
    - name: Run establish a ngrok tunnel
      id: test
      uses: vmactions/ngrok-tunnel@v0.0.1
      with:
        protocol: tcp
        port: 22 
    - run: brew install --cask chromium
